#import "@preview/diagraph:0.3.6": *
#import "@preview/chic-hdr:0.5.0": *
#import "@preview/rexllent:0.4.0": *

#show heading: set block(above: 2em)
#show heading: set block(below: 1em)
#show link: it => underline(text(fill: blue)[#it])
#let numberingH(c) = {
    if c.numbering != none {
        return numbering(c.numbering, ..counter(heading).at(c.location()))
    }
    return ""
}

#let currentH(level) = {
    let elems = query(selector(heading.where(level: level)).after(here()))

    if elems.len() != 0 and elems.first().location().page() == here().page() {
        return [#numberingH(elems.first()) #elems.first().body]
    } else {
        elems = query(selector(heading.where(level: level)).before(here()))
        if elems.len() != 0 {
            return [#numberingH(elems.last()) #elems.last().body]
        }
    }
    return ""
}

#set page(
    paper: "a4",
    margin: (x: 2.5cm, y: 2.5cm),
    number-align: right,
)

#set par(
    justify: true,
)

#set text(
    font: "New Computer Modern",
    size: 12pt
)

#set heading(
    numbering: "1.1 ",
)

#let ansline = line(
    start: (0%, 0%),
    end: (100%, 0%),
    stroke: (thickness: 1pt, dash: "dashed")
)

#let abstrue = text([`true`])
#let absfalse = text([`false`])
#let absand = text([`and`])
#let absor = text([`or`])
#let absnot = text([`not`])

#let title = "Context Free Languages 3"
#let subtitle = "Parser Generators -- Abstract Syntax & Demo"
#let subject = "02141 Computer Science Modelling"
#let date = "March 3rd, 2026"

#let author = (if read("../.secret").trim() == "" { "name" } else { read("../.secret").trim() },)

#align(center)[
    #v(24pt)
    #text(32pt)[#smallcaps(title)]
    #v(-24pt)
    #text(16pt)[#subtitle]
    #v(-10pt)
    #text(fill:black.lighten(25%), [#subject])
    #grid(columns: (1fr,) * author.len(),
        column-gutter: 2pt,
        ..author.map(a => align(center)[#a])
    )
    #v(-2pt)
    #text(12pt)[#date]
]

//#v(16pt)
//#grid(columns: (1cm, 1fr, 1cm),
//    column-gutter: 2pt,
//    [],
//    [],
//    []
//)

#outline()

#show heading.where(level: 1): it => pagebreak(weak: true) + it

#pagebreak()


= Abstract syntax for boolean expressions
Consider again the following grammar for boolean expressions:
$
    B -> abstrue | B absor B | absnot B | (B)
$

== Design a functional datatype that is suitable to represent abstract syntax for boolean expressions generated by the grammar, and show a statement that represents the expression: $absnot (abstrue absor abstrue)$. Use F\# or any other functional language of your choice.




== Design a set of classes/structures that are suitable to represent abstract syntax for boolean expressions generated by the grammar, and show a program statement to build the abstract syntax for the above expression. Use Java or any other imperative language of your choice.




= Generating Abstract Syntax





