#import "@preview/diagraph:0.3.6": *

#show heading: set block(above: 2em)
#show heading: set block(below: 1em)
#show link: it => underline(text(fill: blue)[#it])
#show heading.where(level: 3): set heading(outlined: false)

#set page(
    paper: "a4",
    margin: (x: 2.5cm, y: 2.5cm),
    numbering: "1 of 1",
    number-align: right,
    header: none
)

#set par(
    justify: true,
)

#set text(
    font: "New Computer Modern",
    size: 12pt
)

#set heading(
    numbering: "1.1 ",
)

#let ansline = line(
    start: (0%, 0%),
    end: (100%, 0%),
    stroke: (thickness: 1pt, dash: "dashed")
)

#let title = "Context Free Languages 1"
#let subtitle = "Introduction to CFGs"
#let subject = "02141 Computer Science Modelling"
#let date = "February 24th, 2026"

#let author = (if read("../.secret").trim() == "" { "name" } else { read("../.secret").trim() },)

#align(center)[
    #text(32pt)[#smallcaps(title)] \ #text(18pt)[#subtitle] \ #text(fill:black.lighten(25%), [#subject])
]

#{
    grid(columns: (1fr,) * author.len(),
        column-gutter: 2pt,
        ..author.map(a => align(center)[#a])
    )
}

#align(center)[
    #date
]


//#pagebreak()
#outline()

//#v(16pt)
//#grid(columns: (1cm, 1fr, 1cm),
//    column-gutter: 2pt,
//    [],
//    [],
//    []
//)

    

#pagebreak()


= Exercise 1.1
Design context-free grammars for the following languages. Note that $n$ and $m$ are natural numbers.


== ${0^n | n >= 0}$, i.e. the set of all strings made of zero or more 0's.


== ${0^n | n >= 1}$, i.e. the set of all strings made of one or more 0's


== ${O^n 1^m | n >= 1 and m >= 1}$, i.e. the set of all strings made of one or more 0's followed by one or more 1's.


== ${0^n 1^n | n >= 1}$, i.e. the set of all strings made by one or more 0's followed by an equal number of 1's.



= Exercise 5.1.2
The following grammar generates the language of regular expression $0^* 1 (0 + 1)^*$:
$
    S &-> A 1 B \
    A &-> 0 A | epsilon \
    B &-> 0 B | 1 B | epsilon
$
Give leftmost and rightmost deriviations of the following strings:

== \* 00101.


== 1001.


= Exercise 5.1.1
== For the grammar and each of the strings in the previous exercise, give parse trees.





= Grammars for non-regular languages
Provide context-free grammars for each of the following languages.

== The set of strings of balanced parenthesies. These are the strings of characters "(" and ")" that can appear in a well-formed artihmetic expression.


== \* {0^n 10^n | n >= 1}.


== ${0^n 1^m 2^n | n #text("and") m #text("are arbitrary integers")}$.


== ${0^n 1^m | n <= m}$.


== ${0^n 1^(2n) | n >= 1}$.




= Grammars for lists
Let $A$ be a set of elements. You can assume that elements in $A$ are generated by a non-terminal $A$ and you can consider a simple case for $A$ (for example, the alphabet ${0, 1}$).

Recall that a list can be inductively defined: a list of elements of $A$ can be
- the empty list;
- or a single element of $A$ followed by a list of elements of A;

You are free to decide the format of the lists. It can be something like a `CSV` format, the way your favourite programming language outputs lists, etc. Start by writing down some examples of lists and then design a grammar that would accept your example.

== Design a  context-free grammar for lists if elements belonging to $A$.



= Grammars for trees
Let $A$ be a set of elements. You can assume that elements in $A$ are generated by a non-terminal $A$ and you can considder a simple case for $A$ (for example, the alphabet ${0, 1}$). Recall that trees can be inductively defined: a tree with leafs from $A$ can be
- the empty tree;
- or a node with a left sub-tree with leafs from $A$ and a right tree with leaf from $A$.

You are free to decide the format of trees, i.e. how trees should be write down as a string. It can be something inspired by XML, for example. Start by writing down some examples of trees, and how you would represent them as a string. Design then a grammar that would accept your examples

== Design a context free grammar for binary trees with leafs belonging to $A$.






= Grammars for Dictionaries



































